name: OWASP ZAP Full Security Scan

on:
  push:
    branches:
      - main

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    name: Full Scan of the Web Application

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "owasp/zap2docker-stable"
          target: "https://burpsuite.bulb.cloud"
          cmd_options: '-z "-configFile /zap/wrk/options.prop" -J zap_report.json -w zap_report.md -r zap_report.html'

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-reports
          path: |
            zap_report.json
            zap_report.md
            zap_report.html
