name: gitleaks
on: [pull_request, push, workflow_dispatch]
permissions:
  contents: read
  pull-requests: read
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@e6dab246340401bf53eec993b8f05aebe80ac636
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
